ARG build_variant=full

FROM python:3.13.2-alpine3.21 AS base

WORKDIR /app

RUN apk add uv git
RUN addgroup -S limgroup
RUN adduser -S limited -G limgroup
RUN chown limited:limgroup /app

COPY --chown=limited:limgroup . .
RUN chmod +x ./start.sh

USER limited

FROM base AS sync_full
RUN uv sync --all-groups

FROM base AS sync_min
RUN uv sync

FROM sync_${build_variant} AS final
CMD ./start.sh
