site_name: Fastscaffold
repo_url: https://github.com/Tapeline/Fastscaffold
copyright: © Copyright Tapeline 2025
site_url: https://tapeline.github.io/Fastscaffold
nav:
  - Home: index.md
  - Getting started:
      - Install: getting_started/install.md
      - Create first app: getting_started/create_first_app.md
  - Components:
      - Commons:
          - Data commons: components/commons/data.md
      - Domain:
          - Entity: components/domain/entity.md
      - Application:
          - Auth & user: components/application/auth.md
          - Common interactors: components/application/interactors.md
          - Persistence: components/application/storage.md
      - Infrastructure:
          - Persistence: components/infrastructure/persistence.md
          - Security algorithms: components/infrastructure/security.md
      - Presentation:
          - Litestar: components/presentation/litestar.md
      - Bootstrap:
          - Config: a
          - Litestar: a
          - DI: a
      - Packaging:
          - Docker: a
          - Python project: a
      - Tools:
          - QA configs: a
      - Tests:
          - Pytest: a
  - Contributing: contributing.md

theme:
  name: material2014
  primary_color: "#03A9F4"

plugins:
  - macros:
      module_name: docs/macros
  - mermaid2
  - ezglossary:
      tooltip: full
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - def_list
  - material2014.extensions.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true